### PR TITLE
Rework the interface of `PersistentTabView`

### PR DESCRIPTION
**Pull request by jb3rndt**
This should make the `PersistentTabView` more understandable and robust, expecially when using a custom navbar.

ToDo:

- [x] Remove `PersistentTabViewBase` which was just wrapped by `PersistentTabView`
- [x] Make the navbar a builder
- [x] Move `itemAnimationProperties` out of `PersistentTabView` and pass it to the NavBar directly
- [x] Move `navBarDecoration` out of `PersistentTabView` and pass it to the NavBar directly
- [x] `backgroundColor` changes navbar color -> move into navBarDecoration
- [x] Move `neumorphicProperties` out of `PersistentTabView` and pass it to the NavBar directly
- [x] Rework `PersistentBottomNavBarItem` to directly set the correct values for the colors
- [x] Unify primary color and secondary color scheme
- [x] Migration guide

### CODE REVIEW

**Comment by DynxstyGIT** [comment]
Is there an ETA on when this will be released?

**Comment by jb3rndt** [comment]
Not really, but it is currently released in a beta state, so I'm happy about everyone testing the changes, migrating and providing feedback in any regards to make it easier and more understandable. So feel free to try it out: https://pub.dev/packages/persistent_bottom_nav_bar_v2/versions/5.0.0-beta.1

**Comment by DynxstyGIT** [comment]
What exactly happened to `pushDynamic` screen in the latest beta?
I used it to push a `ModalRoute<void>`

**Comment by DynxstyGIT** [comment]
I just saw that you've added support for the Drawer - Could you also add `drawerEdgeDragWidth`? 🙏

**Comment by jb3rndt** [comment]
Sure, should be available with version 5.0.0-beta.4 now

**Pull request merged**
